/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DAO.connectionDB;
import DAO.dichVuDao;
import DAO.khachHangDao;
import DAO.loaiPhongDao;
import MODEL.hoTRo;
import POJO.dichVu;
import POJO.khachHang;
import com.sun.xml.internal.ws.spi.db.DatabindingProvider;
import java.awt.List;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import jdk.internal.org.objectweb.asm.commons.GeneratorAdapter;
import sun.security.x509.GeneralNames;

/**
 *
 * @author thuha
 */
public final class KHACHHANG extends javax.swing.JFrame {

    DefaultTableModel modelTB;
    Vector tbTile = new Vector();
    ArrayList<khachHang> ds;

    /**
     * Creates new form KHACHHANG
     *
     * @param tentk
     */
    public KHACHHANG() {
        initComponents();

        setLocationRelativeTo(null);
        tbTile.add("Mã KH");
        tbTile.add("Tên KH");
        tbTile.add("Giới Tính");
        tbTile.add("Địa Chỉ");
        tbTile.add("Số ĐT");
        modelTB = new DefaultTableModel();
        modelTB.setColumnIdentifiers(tbTile);
        tb_dskhach_search.setModel(modelTB);
        tb_dskhachhang.setModel(modelTB);
        lb_soluongkhach.setText(khachHangDao.demSL_Khach());
        loadDuLieu();

    }

    void loadDuLieu() {
        ds = khachHangDao.getDSKHang();
        modelTB.setRowCount(0);
        for (khachHang kh : ds) {
            Vector v = new Vector();
            v.add(kh.getMaKH());
            v.add(kh.getTenKH());
            v.add(kh.getGioiTinh());
            v.add(kh.getDiaChi());
            v.add(kh.getSoDT());

            modelTB.addRow(v);
        }

    }

    public void reset() {
        txt_makh.setText("");
        txt_tenkh.setText("");
        txt_gioitinh.setText("");

        txt_diachi.setText("");
        txt_sodt.setText("");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        btn_thoat = new javax.swing.JButton();
        btn_xoa = new javax.swing.JButton();
        btn_load_data_txt = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_makh = new javax.swing.JTextField();
        txt_tenkh = new javax.swing.JTextField();
        txt_diachi = new javax.swing.JTextField();
        txt_sodt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_dskhachhang = new javax.swing.JTable();
        txt_gioitinh = new javax.swing.JTextField();
        btn_huy = new javax.swing.JButton();
        btn_sua = new javax.swing.JButton();
        btn_luuxuong_txt = new javax.swing.JButton();
        btn_luu = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        lb_soluongkhach = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tb_dskhach_search = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        btn_exit = new javax.swing.JButton();
        btn_timkiem = new javax.swing.JButton();
        txt_timtenkhach = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("QUẢN LÝ KHÁCH HÀNG");

        jTabbedPane1.setBackground(new java.awt.Color(255, 153, 0));
        jTabbedPane1.setForeground(new java.awt.Color(0, 102, 102));
        jTabbedPane1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        btn_thoat.setBackground(new java.awt.Color(255, 204, 204));
        btn_thoat.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btn_thoat.setForeground(new java.awt.Color(102, 0, 102));
        btn_thoat.setText("ĐÓNG");
        btn_thoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_thoatActionPerformed(evt);
            }
        });

        btn_xoa.setBackground(new java.awt.Color(255, 204, 204));
        btn_xoa.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btn_xoa.setForeground(new java.awt.Color(102, 0, 102));
        btn_xoa.setText("XÓA");
        btn_xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoaActionPerformed(evt);
            }
        });

        btn_load_data_txt.setBackground(new java.awt.Color(255, 204, 204));
        btn_load_data_txt.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btn_load_data_txt.setForeground(new java.awt.Color(102, 0, 102));
        btn_load_data_txt.setText("NHAP_TXT");
        btn_load_data_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_load_data_txtActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setText("DANH SÁCH KHÁCH HÀNG");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 0, 0));
        jLabel3.setText("MaKH:");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 0, 0));
        jLabel4.setText("TenKH:");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 0, 0));
        jLabel5.setText("GioiTinh:");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 0, 0));
        jLabel6.setText("DiaChi:");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 0, 0));
        jLabel7.setText("SoDT:");

        tb_dskhachhang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "MaKH", "TenKH", "GioiTinh", "DiaCHi", "SDT"
            }
        ));
        tb_dskhachhang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tb_dskhachhangMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tb_dskhachhang);

        btn_huy.setBackground(new java.awt.Color(255, 204, 204));
        btn_huy.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btn_huy.setForeground(new java.awt.Color(102, 0, 102));
        btn_huy.setText("HỦY");
        btn_huy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_huyActionPerformed(evt);
            }
        });

        btn_sua.setBackground(new java.awt.Color(255, 204, 204));
        btn_sua.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btn_sua.setForeground(new java.awt.Color(102, 0, 102));
        btn_sua.setText("SỬA");
        btn_sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_suaActionPerformed(evt);
            }
        });

        btn_luuxuong_txt.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btn_luuxuong_txt.setText("PRINT_TXT");
        btn_luuxuong_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_luuxuong_txtActionPerformed(evt);
            }
        });

        btn_luu.setBackground(new java.awt.Color(255, 204, 204));
        btn_luu.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btn_luu.setForeground(new java.awt.Color(102, 0, 102));
        btn_luu.setText("THEM");
        btn_luu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_luuActionPerformed(evt);
            }
        });

        jButton4.setText("MENU_NV>>");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel9.setText("SO LUONG KH:");

        lb_soluongkhach.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lb_soluongkhach.setText("jLabel10");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(33, 33, 33))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_luu, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_sua, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_huy, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn_thoat)
                                .addGap(67, 67, 67))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lb_soluongkhach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(12, 12, 12))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(btn_load_data_txt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_makh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(16, 16, 16))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel4)))
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txt_gioitinh, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_tenkh, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txt_diachi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_sodt, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_luuxuong_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton4)))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_makh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_load_data_txt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_tenkh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txt_gioitinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(txt_diachi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(txt_sodt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7)
                                .addGap(59, 59, 59)))
                        .addComponent(btn_luuxuong_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btn_sua)
                                .addComponent(btn_huy)
                                .addComponent(lb_soluongkhach)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btn_luu)
                                .addComponent(btn_xoa))
                            .addComponent(btn_thoat))))
                .addGap(46, 46, 46))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btn_load_data_txt, btn_thoat, btn_xoa});

        jTabbedPane1.addTab("Quản Lý Khách Hàng ", jPanel1);

        tb_dskhach_search.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        tb_dskhach_search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tb_dskhach_searchMouseReleased(evt);
            }
        });
        jScrollPane4.setViewportView(tb_dskhach_search);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("DANH SÁCH KHÁCH HÀNG");

        btn_exit.setBackground(new java.awt.Color(51, 51, 51));
        btn_exit.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btn_exit.setForeground(new java.awt.Color(204, 204, 255));
        btn_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/logout-icon-32.png"))); // NOI18N
        btn_exit.setText("THOÁT");
        btn_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exitActionPerformed(evt);
            }
        });

        btn_timkiem.setBackground(new java.awt.Color(51, 51, 51));
        btn_timkiem.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btn_timkiem.setForeground(new java.awt.Color(204, 204, 255));
        btn_timkiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/search-icon-32.png"))); // NOI18N
        btn_timkiem.setText("SEARCH");
        btn_timkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_timkiemActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setText("Mã Khách:");

        jButton2.setText("LoadData");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton3.setText("THÔNG TIN CHI TIẾT CỦA KHÁCH ");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton1.setText("MENU>>");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(btn_timkiem, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_exit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton3)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txt_timtenkhach, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(22, 22, 22))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btn_exit, btn_timkiem});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_timtenkhach, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8)))
                .addGap(32, 32, 32)
                .addComponent(jButton3)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_timkiem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_exit))
                .addContainerGap())
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btn_exit, btn_timkiem});

        jTabbedPane1.addTab("Tìm Kiếm Khách Hàng ", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 638, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_thoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_thoatActionPerformed
        setVisible(false);
        new QL_NhanVien().setVisible(true);
        dispose();
// TODO add your handling code here:
    }//GEN-LAST:event_btn_thoatActionPerformed

    private void tb_dskhachhangMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_dskhachhangMouseReleased
        int row = tb_dskhachhang.getSelectedRow();
        if (row >= 0) {
            txt_makh.setText((String) (tb_dskhachhang.getValueAt(row, 0)));
            txt_tenkh.setText((String) (tb_dskhachhang.getValueAt(row, 1)));
            txt_gioitinh.setText((String) (tb_dskhachhang.getValueAt(row, 2)));
            txt_diachi.setText((String) (tb_dskhachhang.getValueAt(row, 3)));
            txt_sodt.setText((String) (tb_dskhachhang.getValueAt(row, 4)));   // TODO add your handling code here:

        }
    }//GEN-LAST:event_tb_dskhachhangMouseReleased

    private void btn_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exitActionPerformed
        int a = JOptionPane.showConfirmDialog(null, "Do you quan exit", "Thong bao!!", JOptionPane.YES_NO_OPTION);
        if (a == JOptionPane.YES_OPTION) {
            System.exit(0);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btn_exitActionPerformed

    private void btn_load_data_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_load_data_txtActionPerformed
        JFileChooser file = new JFileChooser();
        file.showOpenDialog(this);
        try {
            String filename = file.getSelectedFile().getAbsolutePath();
            String sql = "EXEC SP_NHAPKHACHHANG ?";
            connectionDB.executeQuery(sql);
            loadDuLieu();
            connectionDB.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Chua chon file");
        }

//        String file_name = "D:\\DOAN_DBMS\\KHACHHANG_SQL.txt";
//        File file = new File(file_name);
//        try {
//            BufferedReader br = new BufferedReader(new FileReader(file));
//            String fisline = br.readLine().trim();
//            DefaultTableModel model = (DefaultTableModel) tb_dskhachhang.getModel();
//            Object[] tablelines = br.lines().toArray();
//            for (int i = 0; i < tablelines.length; i++) {
//
//                String[] data = tablelines[i].toString().split(",");
//                model.addRow(data);
//            }
//        } catch (Exception ex) {
//            Logger.getLogger(KHACHHANG.class.getName()).log(Level.SEVERE, null, ex);
//        }
// TODO add your handling code here:
    }//GEN-LAST:event_btn_load_data_txtActionPerformed

    private void btn_huyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_huyActionPerformed
        reset();

    }//GEN-LAST:event_btn_huyActionPerformed

    private void btn_xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoaActionPerformed

        if (hoTRo.checkRong(txt_makh) || hoTRo.checkRong(txt_tenkh) || hoTRo.checkRong(txt_diachi) || hoTRo.checkRong(txt_sodt) || hoTRo.checkRong(txt_gioitinh)) {
            return;

        }
        int tb = tb_dskhachhang.getSelectedRow();
        if (tb >= 0) {
            if (JOptionPane.showConfirmDialog(null, "Ban co muon xoa khong", "Thong bao", 1) == JOptionPane.YES_OPTION) {
                int i = khachHangDao.xoaKH(tb_dskhachhang.getValueAt(tb, 0).toString());

                if (i != -1) {
                    JOptionPane.showMessageDialog(null, "Ban da xoa thanh cong", "Thong bao", 1);
                    loadDuLieu();

                }
            }
        }


    }//GEN-LAST:event_btn_xoaActionPerformed

    private void btn_timkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_timkiemActionPerformed
        if (hoTRo.checkRong(txt_timtenkhach)) {
            return;
        }
        modelTB.setRowCount(0);
        ArrayList<khachHang> dshd = khachHangDao.timB(txt_timtenkhach.getText().trim());

        for (khachHang hv : dshd) {
            Vector r = new Vector();
            r.add(hv.getMaKH());
            r.add(hv.getTenKH());
            r.add(hv.getGioiTinh());
            r.add(hv.getDiaChi());
            r.add(hv.getSoDT());
            modelTB.addRow(r);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_timkiemActionPerformed

    private void tb_dskhach_searchMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_dskhach_searchMouseReleased

        int row = tb_dskhachhang.getSelectedRow();
        txt_makh.setText((String) (tb_dskhachhang.getValueAt(row, 0)));
        txt_tenkh.setText((String) (tb_dskhachhang.getValueAt(row, 1)));
        txt_gioitinh.setText((String) (tb_dskhachhang.getValueAt(row, 2)));
        txt_diachi.setText((String) (tb_dskhachhang.getValueAt(row, 3)));

        // TODO add your handling code here:
    }//GEN-LAST:event_tb_dskhach_searchMouseReleased

    private void btn_suaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_suaActionPerformed

        int row = tb_dskhachhang.getSelectedRow();
        if (row >= 0) {
            if (hoTRo.checkRong(txt_makh) || hoTRo.checkRong(txt_tenkh) || hoTRo.checkRong(txt_diachi) || hoTRo.checkRong(txt_sodt) || hoTRo.checkRong(txt_gioitinh)) {
                return;

            }
            if (!ktraMaKH(txt_makh.getText())) {
                JOptionPane.showMessageDialog(this, "Ma khach co dang KHxx voi x la chu so", "Thong bao", 1);

                txt_makh.setText("");
                txt_makh.requestFocus();

                return;
            }
            if (!hoTRo.ktraSDT(txt_sodt)) {
                return;
            }
            if (!(txt_gioitinh.getText().trim().equals("Nữ") || txt_gioitinh.getText().trim().equals("Nam"))) {
                JOptionPane.showMessageDialog(this, "Giới tính Nam hoặc Nữ", "Thong bao", 1);
                txt_gioitinh.setText("");
                txt_gioitinh.requestFocus();
                return;
            }
            if (JOptionPane.showConfirmDialog(null, "Bạn muốn sửa  khong", "Thông báo", JOptionPane.YES_NO_OPTION, 1) == JOptionPane.YES_OPTION) {
                int i = khachHangDao.updateKH(txt_makh.getText(), txt_tenkh.getText(), txt_gioitinh.getText(), txt_diachi.getText(), txt_sodt.getText());
                if (i != -1) {
                    JOptionPane.showMessageDialog(null, "Đã sửa thanh cong", "Thông báo", 1);

                    loadDuLieu();
                }
            }
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btn_suaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        setVisible(false);
        new QUANLY().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_luuxuong_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_luuxuong_txtActionPerformed

//        JFileChooser Chooser = new JFileChooser();
//        int i = Chooser.showSaveDialog(Chooser);
//        if (i == JFileChooser.APPROVE_OPTION) {
//            File file = Chooser.getSelectedFile();
//            try {
//                FileWriter out = new FileWriter(file + ".xls");
//                BufferedWriter bwrite = new BufferedWriter(out);
//                DefaultTableModel model = (DefaultTableModel) tb_dskhachhang.getModel();
//
//                for (int j = 0; j < tb_dskhachhang.getColumnCount(); j++) {
//                    bwrite.write(model.getColumnName(j) + "\t");
//                }
//                bwrite.write("\n");
//                for (int j = 0; j < tb_dskhachhang.getRowCount(); j++) {
//                    for (int k = 0; k < tb_dskhachhang.getColumnCount(); k++) {
//                        bwrite.write(model.getValueAt(j, k) + "\t");
//                    }
//                    bwrite.write("\n");
//                }
//                bwrite.close();
//                JOptionPane.showMessageDialog(null, "Luu file thanh cong");
//            } catch (Exception e) {
//                JOptionPane.showMessageDialog(null, "Luu file khong  thanh cong");
//
//            }
//        }
        JFileChooser Chooser = new JFileChooser();
        int i = Chooser.showSaveDialog(Chooser);
        if (i == JFileChooser.APPROVE_OPTION) {
            File file = Chooser.getSelectedFile();
            try {
                FileWriter out = new FileWriter(file + ".txt");
                BufferedWriter bwrite = new BufferedWriter(out);
                DefaultTableModel model = (DefaultTableModel) tb_dskhachhang.getModel();

                for (int j = 0; j < tb_dskhachhang.getColumnCount(); j++) {
                    bwrite.write(model.getColumnName(j) + "\t");
                }
                bwrite.write("\n");
                for (int j = 0; j < tb_dskhachhang.getRowCount(); j++) {
                    for (int k = 0; k < tb_dskhachhang.getColumnCount(); k++) {
                        bwrite.write(model.getValueAt(j, k) + "\t");
                    }
                    bwrite.write("\n");
                }
                bwrite.close();
                JOptionPane.showMessageDialog(null, "Luu file thanh cong");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Luu file khong  thanh cong");

            }
        }
//        JFileChooser file = new JFileChooser();
//        file.showOpenDialog(this);
//        String data = "";
//        try {
//            String filename = file.getSelectedFile().getAbsolutePath();
//            for (int i = 0; i < tb_dskhachhang.getRowCount(); i++) {
//                for (int j = 0; j < tb_dskhachhang.getColumnCount(); j++) {
//                    if (tb_dskhachhang.getColumnCount() - 1 == j) {
//                        data += tb_dskhachhang.getValueAt(i, j).toString() + "\n";
//                    } else {
//                        data += tb_dskhachhang.getValueAt(i, j).toString() + ",";
//                    }
//                }
////                DocGhi.getInstane().GhiFile(data, filename + ".txt");
//                String filef = "D:\\DOAN_DBMS\\DS_KhachHang.txt";
//                File file1 = new File(filef);
//
//            }
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(rootPane, "Chua chon file ");
//        }
//        String filef = "src//FILE//DS_KhachHang.txt";
//        File file = new File(filef);
//
//        try {
//            if (JOptionPane.showConfirmDialog(this, "Ban co muon luu vao file txt khong", "Thong bao", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
//
//                FileWriter fw = new FileWriter(file);
//                BufferedWriter bw = new BufferedWriter(fw);
//                JOptionPane.showMessageDialog(this, "Ban da luu file thanh cong", "Thong bao", 2);
//
//                for (int i = 0; i < tb_dskhachhang.getRowCount(); i++) {
//                    for (int j = 0; j < tb_dskhachhang.getColumnCount(); j++) {
//
//                        bw.write(tb_dskhachhang.getValueAt(i, j).toString() + "      ");
//
//                    }
//
//                    bw.newLine();
//                }
//
//                bw.close();
//                fw.close();
//            }
//        } catch (Exception e) {
//        }
    }//GEN-LAST:event_btn_luuxuong_txtActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        tb_dskhach_search.clearSelection();
        loadDuLieu();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed
    boolean ktraMaKH(String maPH) {
        String ktra = "KH\\d+";
        if (maPH.matches(ktra)) {
            return true;
        }
        return false;
    }
    private void btn_luuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_luuActionPerformed

        if (hoTRo.checkRong(txt_makh) || hoTRo.checkRong(txt_tenkh) || hoTRo.checkRong(txt_diachi) || hoTRo.checkRong(txt_sodt) || hoTRo.checkRong(txt_gioitinh)) {
            return;

        }
        if (!ktraMaKH(txt_makh.getText())) {
            JOptionPane.showMessageDialog(this, "Ma khach co dang KHxx voi x la chu so", "Thong bao", 1);

            txt_makh.setText("");
            txt_makh.requestFocus();

            return;
        }
        if (!hoTRo.ktraSDT(txt_sodt)) {
            return;
        }
        if (!(txt_gioitinh.getText().trim().equals("Nữ") || txt_gioitinh.getText().trim().equals("Nam"))) {
            JOptionPane.showMessageDialog(this, "Giới tính Nam hoặc Nữ", "Thong bao", 1);
            txt_gioitinh.setText("");
            txt_gioitinh.requestFocus();
            return;
        }

        if (JOptionPane.showConfirmDialog(this, "Ban co muon them khong", "Thong bao", 1) == JOptionPane.YES_NO_OPTION) {
            int i = khachHangDao.themKH(txt_makh.getText().trim(), txt_tenkh.getText().trim(), txt_gioitinh.getText().trim(), txt_diachi.getText().trim(), txt_sodt.getText().trim());
            if (i != -1) {
                JOptionPane.showMessageDialog(this, "Ban da them thanh cong", "Thong bao", 1);

                loadDuLieu();
                reset();
            }
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btn_luuActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        boolean check = false;
        for (khachHang b : khachHangDao.getDSKHang()) {
            if (b.getMaKH().toLowerCase().trim().equals(txt_timtenkhach.getText().trim().toLowerCase())) {
                check = true;
                break;
            }
        }
        if (!check) {
            JOptionPane.showMessageDialog(null, "Không có mã khach nay", "Thông báo", 1);
            return;
        } else {
            new TT_ChiTiet_Khach(this, rootPaneCheckingEnabled, txt_timtenkhach.getText()).setVisible(true);

        }
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        setVisible(false);
        new QL_NhanVien().setVisible(true);
        dispose(); // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed
//
////    /**
////     * @param args the command line arguments
////     */

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KHACHHANG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KHACHHANG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KHACHHANG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KHACHHANG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new KHACHHANG().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_exit;
    private javax.swing.JButton btn_huy;
    private javax.swing.JButton btn_load_data_txt;
    private javax.swing.JButton btn_luu;
    private javax.swing.JButton btn_luuxuong_txt;
    private javax.swing.JButton btn_sua;
    private javax.swing.JButton btn_thoat;
    private javax.swing.JButton btn_timkiem;
    private javax.swing.JButton btn_xoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JLabel lb_soluongkhach;
    private javax.swing.JTable tb_dskhach_search;
    private javax.swing.JTable tb_dskhachhang;
    private javax.swing.JTextField txt_diachi;
    private javax.swing.JTextField txt_gioitinh;
    private javax.swing.JTextField txt_makh;
    private javax.swing.JTextField txt_sodt;
    private javax.swing.JTextField txt_tenkh;
    private javax.swing.JTextField txt_timtenkhach;
    // End of variables declaration//GEN-END:variables

    private static class TextFileDataToJTable {

        public TextFileDataToJTable() {
        }
    }
}
