/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import MODEL.hoTRo;
import javax.swing.JOptionPane;

/**
 *
 * @author thuha
 */
public class QUANLY extends javax.swing.JFrame {

    String tentk = "";

    /**
     * Creates new form QUANLY
     */
    public QUANLY(String tentk) {
        initComponents();
        this.tentk = tentk;
 hoTRo.clock(lb_cloack);
        setLocationRelativeTo(null);
        lbHello.setText("Xin Chao:"+lbHello.getText() + tentk);
    }

    QUANLY() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        btn_qlphong = new javax.swing.JButton();
        btn_qlnhanvien = new javax.swing.JButton();
        btn_qlloaiphong = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        btn_ttdichvu1 = new javax.swing.JButton();
        lbHello = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lb_cloack = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MENU");

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(153, 0, 153));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/Login-icon-16.png"))); // NOI18N
        jButton1.setText("ĐĂNG XUẤT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btn_qlphong.setBackground(new java.awt.Color(102, 0, 102));
        btn_qlphong.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btn_qlphong.setForeground(new java.awt.Color(0, 255, 102));
        btn_qlphong.setText("QL_PHONG");
        btn_qlphong.setToolTipText("Phòng");
        btn_qlphong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_qlphongActionPerformed(evt);
            }
        });

        btn_qlnhanvien.setBackground(new java.awt.Color(0, 204, 204));
        btn_qlnhanvien.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btn_qlnhanvien.setForeground(new java.awt.Color(255, 102, 102));
        btn_qlnhanvien.setText("QL_NHANVIEN");
        btn_qlnhanvien.setToolTipText("Nhân Viên");
        btn_qlnhanvien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_qlnhanvienActionPerformed(evt);
            }
        });

        btn_qlloaiphong.setBackground(new java.awt.Color(255, 204, 255));
        btn_qlloaiphong.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btn_qlloaiphong.setForeground(new java.awt.Color(255, 0, 255));
        btn_qlloaiphong.setText("QL_LOAIPHONG");
        btn_qlloaiphong.setToolTipText("Loại Phòng");
        btn_qlloaiphong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_qlloaiphongActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(102, 0, 0));
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 204));
        jButton2.setText("EXIT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/menu.jpg"))); // NOI18N
        jButton3.setText("jButton3");

        btn_ttdichvu1.setBackground(new java.awt.Color(255, 255, 0));
        btn_ttdichvu1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btn_ttdichvu1.setForeground(new java.awt.Color(153, 0, 0));
        btn_ttdichvu1.setText("QL_KHACHHANG");
        btn_ttdichvu1.setToolTipText("Khách Hàng");
        btn_ttdichvu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ttdichvu1ActionPerformed(evt);
            }
        });

        lbHello.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N

        lb_cloack.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lb_cloack.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbHello, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btn_qlloaiphong))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(btn_qlphong)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_qlnhanvien)
                            .addComponent(btn_ttdichvu1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(311, 311, 311)
                        .addComponent(lb_cloack)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)))
                .addGap(33, 33, 33))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btn_qlloaiphong, btn_qlnhanvien, btn_qlphong, btn_ttdichvu1});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jButton1))
                    .addComponent(lbHello, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_qlnhanvien)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_ttdichvu1))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btn_qlphong, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(124, 124, 124)
                            .addComponent(btn_qlloaiphong))
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addComponent(lb_cloack))
                .addGap(30, 30, 30))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btn_qlloaiphong, btn_qlnhanvien, btn_qlphong, btn_ttdichvu1});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        setVisible(false);
        new LOGIN().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_qlphongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_qlphongActionPerformed
        setVisible(false);
        new PHONG(tentk).setVisible(true);   
        dispose();// TODO add your handling code here:
    }//GEN-LAST:event_btn_qlphongActionPerformed

    private void btn_qlnhanvienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_qlnhanvienActionPerformed
        setVisible(false);
        new NHANVIEN().setVisible(true);  
        dispose();// TODO add your handling code here:
    }//GEN-LAST:event_btn_qlnhanvienActionPerformed

    private void btn_qlloaiphongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_qlloaiphongActionPerformed
        setVisible(false);
        new LOAIPHONG().setVisible(true); 
        dispose();// TODO add your handling code here:
    }//GEN-LAST:event_btn_qlloaiphongActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        int a = JOptionPane.showConfirmDialog(null, "Do you quan exit", "Thong bao!!", JOptionPane.YES_NO_OPTION);
        if (a == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btn_ttdichvu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ttdichvu1ActionPerformed
        setVisible(false);
        new KHACHHANG().setVisible(true);
        dispose();
// TODO add your handling code here:
    }//GEN-LAST:event_btn_ttdichvu1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QUANLY.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QUANLY.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QUANLY.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QUANLY.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QUANLY().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_qlloaiphong;
    private javax.swing.JButton btn_qlnhanvien;
    private javax.swing.JButton btn_qlphong;
    private javax.swing.JButton btn_ttdichvu1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbHello;
    private javax.swing.JLabel lb_cloack;
    // End of variables declaration//GEN-END:variables
}
