/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DAO.dichVuDao;
import DAO.phongDao;
import DAO.thanhToanDao;
import DAO.thuePhongDao;
import MODEL.hoTRo;
import POJO.phong;
import POJO.thanhToan;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author thuha
 */
public class THANHTOAN extends javax.swing.JFrame {
    String tentk="";

    DefaultTableModel modelTB;
    Vector Tile = new Vector();
    ArrayList<thanhToan> dsp;

    THANHTOAN(String tentk) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public void loadPhong() {
        dsp = thanhToanDao.getdsTT();
        modelTB.setRowCount(0);
        for (thanhToan p : dsp) {
            Vector v = new Vector();
            v.add(p.getMaThueP());
            v.add(p.getThanhTien());
            v.add(p.getNgayTToan());

            modelTB.addRow(v);
        }
    }

    /**
     * Creates new form THANHTOAN
     */
    public THANHTOAN() {
        initComponents();
        setLocationRelativeTo(null);
        this.tentk=tentk;

        Tile.add("Ma Thue Phong");
        Tile.add("Thanh Tien");
        Tile.add("NgayTToan");

        modelTB = new DefaultTableModel();
        modelTB.setColumnIdentifiers(Tile);
        tb_THANHTOA.setModel(modelTB);
        loadPhong();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_THANHTOA = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_mathue = new javax.swing.JTextField();
        txt_thanhtien = new javax.swing.JTextField();
        txt_ngaythanhtoan = new javax.swing.JTextField();
        btn_thoat = new javax.swing.JButton();
        btn_xoa = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btn_sua = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("THÔG TIN THNH TOÁN");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("THÔNG TIN THANH TOÁN");

        tb_THANHTOA.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        tb_THANHTOA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tb_THANHTOAMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tb_THANHTOA);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Mã Thuế:");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Thành Tiền:");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("NgàyTToan:");

        btn_thoat.setBackground(new java.awt.Color(255, 255, 204));
        btn_thoat.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btn_thoat.setForeground(new java.awt.Color(0, 0, 153));
        btn_thoat.setText("ĐÓNG");
        btn_thoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_thoatActionPerformed(evt);
            }
        });

        btn_xoa.setBackground(new java.awt.Color(255, 255, 204));
        btn_xoa.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btn_xoa.setForeground(new java.awt.Color(0, 0, 153));
        btn_xoa.setText("XÓA");
        btn_xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoaActionPerformed(evt);
            }
        });

        jButton1.setText("MENU>>");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btn_sua.setBackground(new java.awt.Color(255, 255, 204));
        btn_sua.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btn_sua.setForeground(new java.awt.Color(0, 0, 153));
        btn_sua.setText("SỬA");
        btn_sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_suaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_thanhtien, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_mathue, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_ngaythanhtoan, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_xoa)
                                .addGap(18, 18, 18)
                                .addComponent(btn_thoat))
                            .addComponent(btn_sua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(63, 63, 63)
                                .addComponent(jButton1)))))
                .addGap(0, 27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jButton1))
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txt_mathue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txt_thanhtien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(btn_sua)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_ngaythanhtoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_thoat)
                            .addComponent(btn_xoa))))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_thoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_thoatActionPerformed
     setVisible(false);
        new QL_NhanVien(tentk).setVisible(true);
        dispose();
        
// TODO add your handling code here:
    }//GEN-LAST:event_btn_thoatActionPerformed
    public void reset() {
        txt_mathue.setText("");
        txt_thanhtien.setText("");
        txt_ngaythanhtoan.setText("");
        txt_mathue.setText("");

    }
    private void btn_xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoaActionPerformed
        if (hoTRo.checkRong(txt_mathue) || hoTRo.checkRong(txt_ngaythanhtoan) || hoTRo.checkRong(txt_thanhtien)) {
            return;
        }
        int row = tb_THANHTOA.getSelectedRow();
        if (row >= 0) {
            int i = dichVuDao.xoaDV(txt_mathue.getText());
            if (i != -1) {
                modelTB.removeRow(row);
                reset();

            }

        }
// TODO add your handling code here:
    }//GEN-LAST:event_btn_xoaActionPerformed

    private void tb_THANHTOAMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_THANHTOAMouseReleased
        int row = tb_THANHTOA.getSelectedRow();
        if (row >= 0) {
            txt_mathue.setText((String) (tb_THANHTOA.getValueAt(row, 0)));
            txt_thanhtien.setText((String) (tb_THANHTOA.getValueAt(row, 1)).toString());
            txt_ngaythanhtoan.setText((String) (tb_THANHTOA.getValueAt(row, 2)).toString());

        }

// TODO add your handling code here:
    }//GEN-LAST:event_tb_THANHTOAMouseReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        setVisible(false);
        new QL_NhanVien(tentk).setVisible(true);
        dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_suaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_suaActionPerformed
    
        int row = tb_THANHTOA.getSelectedRow();
        if (row >= 0) {

             if (hoTRo.checkRong(txt_mathue) || hoTRo.checkRong(txt_ngaythanhtoan) || hoTRo.checkRong(txt_thanhtien)) {
            return;
        }
        if (!ktraMaT(txt_mathue.getText())) {
            JOptionPane.showMessageDialog(this, "Ma thue co dang MTxx voi x la chu so", "Thong bao", 1);

            txt_mathue.setText("");
            txt_mathue.requestFocus();

            return;
        }

        if (!hoTRo.kt_tienThue(Integer.parseInt(txt_thanhtien.getText()))) {
            JOptionPane.showMessageDialog(this, "Thanh tien  phải lớn hơn 0", "Thong bao", 1);
            txt_thanhtien.setText("");
            txt_thanhtien.requestFocus();
            return;

        }
        if (!hoTRo.ktraNgay(txt_ngaythanhtoan)) {
            return;
        }

            int i = thanhToanDao.updateSD(txt_mathue.getText().trim(),Float.parseFloat(txt_thanhtien.getText()),txt_ngaythanhtoan.getText().trim());
            if (i != -1) {
                JOptionPane.showMessageDialog(null, "Sửa thành công", "Thông báo", 1);
                reset();
                loadPhong();
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_suaActionPerformed
    boolean ktraMaT(String maPH) {
        String ktra = "MT\\d+";
        if (maPH.matches(ktra)) {
            return true;
        }
        return false;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(THANHTOAN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(THANHTOAN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(THANHTOAN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(THANHTOAN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new THANHTOAN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_sua;
    private javax.swing.JButton btn_thoat;
    private javax.swing.JButton btn_xoa;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tb_THANHTOA;
    private javax.swing.JTextField txt_mathue;
    private javax.swing.JTextField txt_ngaythanhtoan;
    private javax.swing.JTextField txt_thanhtien;
    // End of variables declaration//GEN-END:variables
}
