/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DAO.dichVuDao;
import DAO.phongDao;
import DAO.suDungDVDao;
import DAO.thanhToanDao;
import DAO.thuePhongDao;
import MODEL.hoTRo;
import POJO.thanhToan;
import POJO.thuePhong;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author thuha
 */
public class THUEPHONG extends javax.swing.JFrame {

    DefaultTableModel modelTB;
    Vector tbTile = new Vector();
    ArrayList<thuePhong> ds;
    String tentk="";

    THUEPHONG(String tentk) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public void loaddata() {
        ds = thuePhongDao.getDSPhong();
        SimpleDateFormat df = new SimpleDateFormat("dd/MM/yyyy");

        modelTB.setRowCount(0);
        for (thuePhong p : ds) {
            Vector v = new Vector();
            v.add(p.getMaThue());
            v.add(p.getMaKH());
            v.add(p.getMaPhong());

            v.add(df.format(p.getNgaVao()));
            v.add(df.format(p.getNgayRa()));
            v.add(p.getTienThueP());

            modelTB.addRow(v);
        }
    }

    /**
     * Creates new form THUEPHONG
     */
    public THUEPHONG() {
        initComponents();
        setLocationRelativeTo(null);
        this.tentk=tentk;

        tbTile.add("Ma Thue");
        tbTile.add("Ma Khach");
        tbTile.add("Ma Phong");
        tbTile.add("Ngay Vao");
        tbTile.add("Ngay Ra");
        tbTile.add("Tien Thue");
        modelTB = new DefaultTableModel();
        modelTB.setColumnIdentifiers(tbTile);
        tb_thongtinthuephong.setModel(modelTB);
        loaddata();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btn_huy = new javax.swing.JButton();
        btn_xoa = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btn_thoat = new javax.swing.JButton();
        txt_mathue = new javax.swing.JTextField();
        txt_makh = new javax.swing.JTextField();
        txt_maphong = new javax.swing.JTextField();
        txt_ngayvao = new javax.swing.JTextField();
        txt_ngayra = new javax.swing.JTextField();
        txt_tienthue = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_thongtinthuephong = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        btn_sua = new javax.swing.JButton();
        btn_them = new javax.swing.JButton();
        btn_luu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("THÔNG TIN THUÊ PHÒNG");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("THÔNG TIN THUÊ PHÒNG");

        btn_huy.setBackground(new java.awt.Color(255, 255, 204));
        btn_huy.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btn_huy.setText("HỦY");
        btn_huy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_huyActionPerformed(evt);
            }
        });

        btn_xoa.setBackground(new java.awt.Color(204, 204, 255));
        btn_xoa.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btn_xoa.setText("XÓA");
        btn_xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoaActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 51));
        jLabel2.setText("Mã Thuê:");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 51));
        jLabel3.setText("Mã Khách:");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 51));
        jLabel4.setText("Mã Phòng:");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 51));
        jLabel5.setText("Ngày Vào:");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 51));
        jLabel6.setText("Ngày Ra:");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 51, 51));
        jLabel7.setText("Tiền Thuê:");

        btn_thoat.setBackground(new java.awt.Color(204, 255, 204));
        btn_thoat.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btn_thoat.setText("ĐÓNG");
        btn_thoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_thoatActionPerformed(evt);
            }
        });

        tb_thongtinthuephong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        tb_thongtinthuephong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tb_thongtinthuephongMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tb_thongtinthuephong);

        jScrollPane2.setViewportView(jScrollPane1);

        jButton1.setText("MENU>>>");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btn_sua.setBackground(new java.awt.Color(255, 255, 204));
        btn_sua.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btn_sua.setText("SỬA");
        btn_sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_suaActionPerformed(evt);
            }
        });

        btn_them.setBackground(new java.awt.Color(255, 255, 204));
        btn_them.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btn_them.setText("THÊM");
        btn_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themActionPerformed(evt);
            }
        });

        btn_luu.setBackground(new java.awt.Color(255, 255, 204));
        btn_luu.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btn_luu.setText("LƯU");
        btn_luu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_luuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(19, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(148, 148, 148)
                                .addComponent(btn_huy))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(82, 82, 82)
                                .addComponent(btn_luu)
                                .addGap(88, 88, 88)
                                .addComponent(btn_sua))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btn_xoa)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn_them)
                                    .addGap(24, 24, 24))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_tienthue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_mathue, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(btn_thoat))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(40, 40, 40)
                                .addComponent(txt_makh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(41, 41, 41)
                                .addComponent(txt_maphong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(41, 41, 41)
                                .addComponent(txt_ngayvao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(41, 41, 41)
                                .addComponent(txt_ngayra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txt_makh, txt_maphong, txt_mathue, txt_ngayra, txt_ngayvao, txt_tienthue});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btn_huy, btn_thoat, btn_xoa});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButton1))
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_mathue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(txt_makh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(txt_maphong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_ngayvao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txt_ngayra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_tienthue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(8, 8, 8)
                        .addComponent(btn_thoat))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btn_xoa)
                                    .addComponent(btn_them))
                                .addGap(12, 12, 12)
                                .addComponent(btn_sua))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_huy)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_luu)))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_thoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_thoatActionPerformed
        setVisible(false);
        new QL_NhanVien(tentk).setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_thoatActionPerformed

    private void tb_thongtinthuephongMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_thongtinthuephongMouseReleased

        int row = tb_thongtinthuephong.getSelectedRow();

        if (row >= 0) {
            txt_mathue.setText((String) (tb_thongtinthuephong.getValueAt(row, 0)));
            txt_makh.setText((String) (tb_thongtinthuephong.getValueAt(row, 1)));
            txt_maphong.setText((String) (tb_thongtinthuephong.getValueAt(row, 2)));
            txt_ngayvao.setText((String) (tb_thongtinthuephong.getValueAt(row, 3)).toString());
            txt_ngayra.setText((String) (tb_thongtinthuephong.getValueAt(row, 4)).toString());

            txt_tienthue.setText((String) (tb_thongtinthuephong.getValueAt(row, 5)).toString());
            btn_sua.setEnabled(true);
            btn_huy.setEnabled(false);
            btn_luu.setEnabled(false);
            btn_xoa.setEnabled(true);
            btn_them.setEnabled(true);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_tb_thongtinthuephongMouseReleased
    public void reset() {
        txt_mathue.setText("");
        txt_makh.setText("");
        txt_maphong.setText("");
        txt_ngayvao.setText("");
        txt_ngayra.setText("");
        txt_tienthue.setText("");
        txt_mathue.requestFocus();
    }
    private void btn_huyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_huyActionPerformed
        reset();

        btn_them.setEnabled(false);

        btn_sua.setEnabled(false);
        btn_xoa.setEnabled(false);

    }//GEN-LAST:event_btn_huyActionPerformed

    private void btn_xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoaActionPerformed

        btn_them.setEnabled(false);
        btn_sua.setEnabled(false);

        btn_huy.setEnabled(true);
        btn_luu.setEnabled(true);

        if (hoTRo.checkRong(txt_mathue) || hoTRo.checkRong(txt_makh) || hoTRo.checkRong(txt_makh) || hoTRo.checkRong(txt_makh) || hoTRo.checkRong(txt_makh) || hoTRo.checkRong(txt_makh)) {
            return;
        }
        int tb = tb_thongtinthuephong.getSelectedRow();
        if (tb >= 0) {
            if (JOptionPane.showConfirmDialog(null, "Ban co muon xoa ", "Thong bao", 1) == JOptionPane.YES_OPTION) {
                int i = thuePhongDao.xoaNHSDDV(tb_thongtinthuephong.getValueAt(tb, 0).toString());
                if (i != -1) {
                    JOptionPane.showMessageDialog(null, "Ban da xoa thanh cong", "Thong bao", 1);
                    loaddata();

                }
            }
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btn_xoaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        setVisible(false);
        new QL_NhanVien(tentk).setVisible(true);
        dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_suaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_suaActionPerformed
        btn_xoa.setEnabled(false);
        btn_them.setEnabled(false);

        btn_luu.setEnabled(true);
        btn_huy.setEnabled(true);
        int row = tb_thongtinthuephong .getSelectedRow();
        if (row >= 0) {
        
            if (hoTRo.checkRong(txt_makh) || hoTRo.checkRong(txt_maphong) || hoTRo.checkRong(txt_mathue)
                    || hoTRo.checkRong(txt_ngayra) || hoTRo.checkRong(txt_ngayvao) || hoTRo.checkRong(txt_tienthue)) {
                return;
            }
            if (!hoTRo.ktraNgay(txt_ngayvao) || !hoTRo.ktraSDT(txt_ngayra)) {
                return;
            }
            Date ngayVao, ngayRa;
        SimpleDateFormat df = new SimpleDateFormat("dd/MM/yyyy");
        try {
            ngayVao = df.parse(txt_ngayvao.getText().trim());
            ngayRa = df.parse(txt_ngayra.getText().trim());
        } catch (Exception e) {
            System.out.println("");
            return;
        }
        System.out.println(ngayVao + " " + ngayRa);
        if (ngayVao.compareTo(ngayRa) >= 0) {
            JOptionPane.showMessageDialog(null, "Ngay muon luon nho hon hoac bang ngay tra", "thong bao", 1);
            return;
        }
            int i = thuePhongDao.updateSD(txt_mathue.getText().trim(), txt_makh.getText().trim(), txt_maphong.getText().trim(), txt_ngayvao.getText().trim(),txt_ngayra.getText().trim(), Integer.parseInt(txt_tienthue.getText()));
            if (i != -1) {
                JOptionPane.showMessageDialog(null, "Sửa thành công", "Thông báo", 1);
                reset();
                loaddata();
            }
        }

    }//GEN-LAST:event_btn_suaActionPerformed

    private void btn_themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themActionPerformed
        reset();

        btn_huy.setEnabled(true);
        btn_luu.setEnabled(true);

        btn_sua.setEnabled(false);
        btn_xoa.setEnabled(false);        // TODO add your handling code here:
    }//GEN-LAST:event_btn_themActionPerformed
    boolean ktraMaTh(String maThue) {
        String ktra = "MT\\d+";
        if (maThue.matches(ktra)) {
            return true;
        }
        return false;
    }

    boolean ktraMaKH(String maKH) {
        String ktra = "KH\\d+";
        if (maKH.matches(ktra)) {
            return true;
        }
        return false;
    }

    boolean ktraMaPhong(String maPH) {
        String ktra = "MP\\d+";
        if (maPH.matches(ktra)) {
            return true;
        }
        return false;
    }

    private void btn_luuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_luuActionPerformed
        if (hoTRo.checkRong(txt_makh) || hoTRo.checkRong(txt_maphong) || hoTRo.checkRong(txt_mathue)
                || hoTRo.checkRong(txt_ngayra) || hoTRo.checkRong(txt_ngayvao) || hoTRo.checkRong(txt_tienthue)) {
            return;
        }
        if (!ktraMaTh(txt_mathue.getText())) {
            JOptionPane.showMessageDialog(this, "Ma thue co dang MTxx voi x la chu so", "Thong bao", 1);

            txt_mathue.setText("");
            txt_mathue.requestFocus();

            return;
        }
        if (!ktraMaKH(txt_makh.getText())) {
            JOptionPane.showMessageDialog(this, "Ma khach co dang KHxx voi x la chu so", "Thong bao", 1);

            txt_makh.setText("");
            txt_makh.requestFocus();

            return;
        }
        if (!ktraMaPhong(txt_maphong.getText())) {
            JOptionPane.showMessageDialog(this, "Ma thue co dang MPxx voi x la chu so", "Thong bao", 1);

            txt_maphong.setText("");
            txt_maphong.requestFocus();

            return;
        }
        if (!hoTRo.kt_tienThue(Integer.parseInt(txt_tienthue.getText()))) {
            JOptionPane.showMessageDialog(this, "Tien thue phải lớn hơn 0", "Thong bao", 1);
            txt_tienthue.setText("");
            txt_tienthue.requestFocus();
            return;

        }
        if (!hoTRo.ktraNgay(txt_ngayvao) || !hoTRo.ktraNgay(txt_ngayra)) {
            return;
        }

        Date ngayVao, ngayRa;
        SimpleDateFormat df = new SimpleDateFormat("dd/MM/yyyy");
        try {
            ngayVao = df.parse(txt_ngayvao.getText().trim());
            ngayRa = df.parse(txt_ngayra.getText().trim());
        } catch (Exception e) {
            System.out.println("");
            return;
        }
        System.out.println(ngayVao + " " + ngayRa);
        if (ngayVao.compareTo(ngayRa) >= 0) {
            JOptionPane.showMessageDialog(null, "Ngay muon luon nho hon hoac bang ngay tra", "thong bao", 1);
            return;
        }

        if (JOptionPane.showConfirmDialog(this, "Ban co muon them khong", "Thong bao", 1) == JOptionPane.YES_NO_OPTION) {
            int i = thuePhongDao.themNT(txt_mathue.getText().trim(), txt_makh.getText().trim(),
                    txt_maphong.getText().trim(), txt_ngayvao.getText().trim(), txt_ngayra.getText().trim(),
                    Integer.parseInt(txt_tienthue.getText()));
            if (i != -1) {
                JOptionPane.showMessageDialog(this, "Ban da them thanh cong", "Thong bao", 1);

                loaddata();
                reset();
            }
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btn_luuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(THUEPHONG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(THUEPHONG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(THUEPHONG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(THUEPHONG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new THUEPHONG().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_huy;
    private javax.swing.JButton btn_luu;
    private javax.swing.JButton btn_sua;
    private javax.swing.JButton btn_them;
    private javax.swing.JButton btn_thoat;
    private javax.swing.JButton btn_xoa;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tb_thongtinthuephong;
    private javax.swing.JTextField txt_makh;
    private javax.swing.JTextField txt_maphong;
    private javax.swing.JTextField txt_mathue;
    private javax.swing.JTextField txt_ngayra;
    private javax.swing.JTextField txt_ngayvao;
    private javax.swing.JTextField txt_tienthue;
    // End of variables declaration//GEN-END:variables
}
