/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DAO.loaiPhongDao;
import DAO.nhanVienDao;
import MODEL.hoTRo;
import POJO.loaiPhong;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author thuha
 */
public class LOAIPHONG extends javax.swing.JFrame {

    DefaultTableModel modelTB;
    Vector tbTile = new Vector();
    String tentk = "";

    ArrayList<loaiPhong> ds;

    /**
     * Creates new form LOAIPHONG
     */
    public LOAIPHONG() {
        initComponents();
        this.tentk = tentk;

        setLocationRelativeTo(null);

        tbTile.add("Mã loại phòng ");
        tbTile.add("Tên loại phòng");
        modelTB = new DefaultTableModel();
        modelTB.setColumnIdentifiers(tbTile);
        tb_dsloaiphong.setModel(modelTB);
        loaddulieu();
    }

    LOAIPHONG(String tentk) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public void loaddulieu() {
        ds = loaiPhongDao.getDSLoai();
        modelTB.setRowCount(0);
        for (loaiPhong p : ds) {
            Vector v = new Vector();
            v.add(p.getMaLoai());
            v.add(p.getTenLoai());
            modelTB.addRow(v);

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnsua = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        btbthoat = new javax.swing.JButton();
        txt_maloaiphong = new javax.swing.JTextField();
        txt_tenloaiphong = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btnthem = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb_dsloaiphong = new javax.swing.JTable();
        btn_reset = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("QUAN LY LOAI PHONG");

        btnsua.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnsua.setText("Sửa");
        btnsua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsuaActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel9.setText("DANH MỤC LOẠI PHÒNG");

        btbthoat.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btbthoat.setText("ĐÓNG");
        btbthoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbthoatActionPerformed(evt);
            }
        });

        txt_maloaiphong.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        txt_tenloaiphong.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("Tên Loại:");

        btnthem.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnthem.setText("Thêm");
        btnthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("Mã Loại:");

        tb_dsloaiphong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        tb_dsloaiphong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tb_dsloaiphongMouseReleased(evt);
            }
        });
        jScrollPane2.setViewportView(tb_dsloaiphong);

        jScrollPane1.setViewportView(jScrollPane2);

        btn_reset.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btn_reset.setText("Reset");
        btn_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetActionPerformed(evt);
            }
        });

        jButton1.setText("MENU>>>");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(jLabel9))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_maloaiphong, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_tenloaiphong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(btnsua, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(btnthem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_reset)
                .addGap(78, 78, 78)
                .addComponent(btbthoat, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txt_maloaiphong, txt_tenloaiphong});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btbthoat, btn_reset, btnthem});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txt_maloaiphong, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_tenloaiphong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnsua, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnthem)
                    .addComponent(btbthoat)
                    .addComponent(btn_reset))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txt_maloaiphong, txt_tenloaiphong});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btbthoat, btn_reset, btnsua, btnthem});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btbthoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbthoatActionPerformed
     setVisible(false);
        new QL_NhanVien(tentk).setVisible(true);
        dispose();   // TODO add your handling code here:
    }//GEN-LAST:event_btbthoatActionPerformed

    private void tb_dsloaiphongMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_dsloaiphongMouseReleased

        int row = tb_dsloaiphong.getSelectedRow();
        if (row >= 0) {
            txt_maloaiphong.setText((String) (tb_dsloaiphong.getValueAt(row, 0)));
            txt_tenloaiphong.setText((String) (tb_dsloaiphong.getValueAt(row, 1)));
        }
    }//GEN-LAST:event_tb_dsloaiphongMouseReleased
    boolean ktraMaLP(String maPH) {
        String ktra = "LP\\d+";
        if (maPH.matches(ktra)) {
            return true;
        }
        return false;
    }
    private void btnthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemActionPerformed

        if (hoTRo.checkRong(txt_maloaiphong) || hoTRo.checkRong(txt_tenloaiphong)) {
            return;
        }
        if (!ktraMaLP(txt_maloaiphong.getText())) {
            JOptionPane.showMessageDialog(this, "Ma loai phongco dang LPxx voi x la chu so", "Thong bao", 1);

            txt_maloaiphong.setText("");
            txt_maloaiphong.requestFocus();

            return;
        }

        if (JOptionPane.showConfirmDialog(this, "Ban co muon them khong", "Thong bao", 1) == JOptionPane.YES_NO_OPTION) {
            int i = loaiPhongDao.thenLoaiPhong(txt_maloaiphong.getText().trim(), txt_tenloaiphong.getText().trim());
            if (i != -1) {
                JOptionPane.showMessageDialog(this, "Ban da them thanh cong", "Thong bao", 1);

                loaddulieu();
                reset();
            }
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnthemActionPerformed

    private void btnsuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsuaActionPerformed

        int row = tb_dsloaiphong.getSelectedRow();
        if (row >= 0) {

            if (hoTRo.checkRong(txt_maloaiphong) || hoTRo.checkRong(txt_tenloaiphong)) {
                return;
            }
            if (!ktraMaLP(txt_maloaiphong.getText())) {
                JOptionPane.showMessageDialog(this, "Ma loai phongco dang LPxx voi x la chu so", "Thong bao", 1);

                txt_maloaiphong.setText("");
                txt_maloaiphong.requestFocus();

                return;
            }
            if (JOptionPane.showConfirmDialog(null, "Bạn muốn sửa  khong", "Thông báo", JOptionPane.YES_NO_OPTION, 1) == JOptionPane.YES_OPTION) {
                int i = loaiPhongDao.updateLoaiP(txt_maloaiphong.getText(), txt_tenloaiphong.getText());
                if (i != -1) {
                    JOptionPane.showMessageDialog(null, "Đã sửa thanh cong", "Thông báo", 1);

                    loaddulieu();
                }
            }
        }


    }//GEN-LAST:event_btnsuaActionPerformed
    public void reset() {
        txt_maloaiphong.setText("");
        txt_tenloaiphong.setText("");
        txt_maloaiphong.requestFocus();
    }
    private void btn_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetActionPerformed
        reset();// TODO add your handling code here:
    }//GEN-LAST:event_btn_resetActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        setVisible(false);
        new QUANLY(tentk).setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed
//
//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(LOAIPHONG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(LOAIPHONG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(LOAIPHONG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(LOAIPHONG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new LOAIPHONG().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btbthoat;
    private javax.swing.JButton btn_reset;
    private javax.swing.JButton btnsua;
    private javax.swing.JButton btnthem;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tb_dsloaiphong;
    private javax.swing.JTextField txt_maloaiphong;
    private javax.swing.JTextField txt_tenloaiphong;
    // End of variables declaration//GEN-END:variables

}
